### ISSUE TITLE
Finish the role

### ISSUE THREAD

**Issue by killua-eu** [Vaizard/mage-smartmontools#1]
Hi @berkas1 , if you're free, could you kindly look into this role tomorrow? The test is a piece of crap, either the `| greo` is wrong or the registered `smart_disabled` gets actually filled with some crap. I'm out of the city and wanna get this one done so that it can be used as an optional dep for https://github.com/vaizard/mage-monit

**Comment by killua-eu** [comment]
Oh and the vars/main.yml override should be tested on fedora. Didn't do that too

**Comment by berkas1** [comment]
Should behave correctly now. Fedora test during the weekend.
